#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 28 11:11:27 2018

@author: maadland
"""

def add_vectors(a_list, b_list):
    """adds two lists together
    """
    c_list = []
    for index, element in enumerate(a_list):
        current_item = element + b_list[index]
        c_list.append(current_item)
    return c_list

if __name__ == "__main__":
    a_list = [1, -2]
    b_list = [-2, 1]
    c_list = add_vectors(a_list, b_list)
    print(c_list)
    # subtraction example 
    d_list = [-1, 2]
    b_list = [1, -z2]
    value = subtract_vectors(d_list, b_list)
    print(value)